# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_PHY_ZHIHE_SNPS_PCIE3) += phy-zhihe-snps-e16phy.o
obj-$(CONFIG_PHY_ZHIHE_SNPS_USB2) += phy-zhihe-snps-usb2.o
obj-$(CONFIG_PHY_ZHIHE_SNPS_C10PHY) += phy-zhihe-snps-c10phy.o